export const Img = {
logo1:require('../../src/assets/onboarding1.png'),
logo2:require('../../src/assets/onboarding2.png'),
logo3:require('../../src/assets/onboarding3.png'),
quotebox:require('../../src/assets/quotebox.png'),
share:require('../../src/assets/share.png'),
copy:require('../../src/assets/copy.png'),
sadcircle:require('../../src/assets/sadcircle.png'),
lifecircle:require('../../src/assets/lifecircle.png'),
lovecircle:require('../../src/assets/lovecircle.png'),
happycircle:require('../../src/assets/happycircle.png'),
happycircle:require('../../src/assets/happycircle.png'),
birdcircle:require('../../src/assets/birdcircle.png'),
travelcircle:require('../../src/assets/travelcircle.png'),
trustcircle:require('../../src/assets/trustcircle.png'),
friendscircle:require('../../src/assets/friendscircle.png'),
plus:require('../../src/assets/plus.png'),
home:require('../../src/assets/home.png'),
save:require('../../src/assets/save.png'),
gallery:require('../../src/assets/gallery.png'),
blackgallery:require('../../src/assets/blackgallery.png'),
text:require('../../src/assets/text.png'),
textblack:require('../../src/assets/textblack.png'),
textblack:require('../../src/assets/textblack.png'),
property:require('../../src/assets/property.png'),
propertyblack:require('../../src/assets/propertyblack.png'),
font:require('../../src/assets/font.png'),
fontblack:require('../../src/assets/fontblack.png'),
color:require('../../src/assets/color.png'),
colorblack:require('../../src/assets/colorblack.png'),
colorblack:require('../../src/assets/colorblack.png'),
effect:require('../../src/assets/effect.png'),
effectblack:require('../../src/assets/effectblack.png'),
shadow:require('../../src/assets/shadow.png'),
shadowblack:require('../../src/assets/shadowblack.png'),
colorpicker:require('../../src/assets/colorpicker.png'),
sample1:require('../../src/assets/sample1.png'),
sample2:require('../../src/assets/sample2.png'),
sample3:require('../../src/assets/sample3.png'),
more:require('../../src/assets/more.png'),
roadsample:require('../../src/assets/roadsample.png'),



leftarrow:require('../../src/assets/leftarrow.png'),
bottomlogo:require('../../src/assets/bottomlogo.png'),
bottomlogo2:require('../../src/assets/bottomlogo2.png'),

cancel:require('../../src/assets/cancel.png'),
arrow:require('../../src/assets/arow.png'),
undo:require('../../src/assets/undo.png'),
}